# Railway 설정
$schema: https://railway.app/railway.schema.json
version: 2

deploy:
  startCommand: npm run start:prod
  healthcheckPath: /
  healthcheckTimeout: 300
  restartPolicyType: always

build:
  builder: nixpacks
  buildCommand: npm ci && npm run build
  watchPatterns: ["**"]

variables:
  NODE_ENV: production
  PORT: ${{RAILWAY_PORT}}